services:
  airflow:
    build: .
    volumes:
      - ./dags:/app/dags
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.airflow:/opt/airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - ETL_DB_PATH=/app/data/reddit.db
      - PYTHONPATH=/app/src
    ports:
      - "8080:8080"
    command: standalone
