version: '3.8'
services:
  airflow:
    image: apache/airflow:2.7.3-python3.10
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./.airflow:/opt/airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - ETL_DB_PATH=/opt/airflow/data/reddit.db
    ports:
      - "8080:8080"
    command: standalone
